### ISSUE TITLE
Issue with passing rich text to util library

### ISSUE THREAD

**Issue by TekEffekt** [contentstack/contentstack-utils-swift#4]
Hello! The Brad's Deals mobile team and I have a question regarding your docs.

In this section on the docs:

```
import ContentstackUtils  

let stack:Stack = Contentstack.stack(apiKey: API_KEY, deliveryToken: DELIVERY_TOKEN, environment: ENVIRONMENT)  

stack.contentType(uid: contentTypeUID)
     .entry(uid: entryUID)
     .include(.embeddedItems)  
     .fetch { (result: Result<EntryModel, Error>, response: ResponseType) in  
        switch result {  
            case .success(let model):
                ContentstackUtils.render(content: model.richTextContent, Option(entry: model))  
            case .failure(let error):  
                //Error Message  
        }  
    }
```

It's unclear to us what the `.richTextContent` property is, given that the `EntryModel` type has no such thing.

Thanks!

**Comment by uttamukkoji** [comment]
Hi @TekEffekt ,

In above example `EntryModel` is custom model that we can create in which you have the RTE content with field name `richTextContent` you may have different field name as well in your custom model.

**Comment by akumar-credtishop** [comment]
Hi, What should be the type of richTextContent in our custom model? Also, how to convert that type to string type which should be passed to ContentstackUtils.render(content: model.richTextContent, Option(entry: model))? Do we have any sample project for reference?

**Comment by uttamukkoji** [comment]
Hey @akumar-credtishop ,

Can you please use support@contentstack.com for the above issue? This will help us to understand your scenario and provide solution on same channel.
