### ISSUE TITLE
Invalid Exclude Warnings

### ISSUE THREAD

**Issue by Sireikis** [contentstack/contentstack-utils-swift#5]
Hello, I'm currently getting these package warnings:

Invalid Exclude .../SourcePackages/checkouts/contentstack-utils-swift/Sources/Tests/KannaTests/Data': File not found.
Invalid Exclude .../SourcePackages/checkouts/contentstack-utils-swift/Sources/Sources/Kanna/Info.plist': File not found.
Invalid Exclude .../SourcePackages/checkouts/contentstack-utils-swift/Sources/Sources/Kanna/Kanna.h': File not found.

My understanding of these warnings is that the contentStackUtils Package.swift folder is trying to exclude files that don't exist, because the Kanna package already excludes these files in their own Package.swift file.

Would it be possible to remove these excludes in the contentStackUtils Package.swift file? If not, is there a way to silence these warnings?

**Comment by uttamukkoji** [comment]
Hi @Sireikis ,

Thanks for raising the issue. We will check this and update you once we resolved this issue. 

Currently there is no way to silence the warning in current Xcode versions.
